version: '3.1'
services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "spring_shot"
    ports:
      - 15215:3306
